[google]
client_id = "911473592132-1n39uif3f6ss0ged5em99ifgnr02l68i.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501"
api_key = "AIzaSyDMrFO1TpptFjSPjfbwv5bMNC2f-XhawsE"

[ai]
openai_api_key = "YOUR_OPENAI_OR_GEMINI_KEY"
